[build-system]
requires = ["setuptools==70.0"]
build-backend = "setuptools.build_meta"

[project]
name = "taina"
dynamic = ["version"]
dependencies = []

[project.optional-dependencies]
dev = [
    "pytest==8.2.1",
    "ruff==0.4.5",
]

[tool.setuptools.dynamic]
version = {attr = "taina.__version__"}

[tool.pytest.ini_options]
testpaths = ["test"]
